
export enum VehicleTypeEnumDto {
  RDTU = "RDTU",
  PERSON = "PERSON",
  RC = "RC",
  RDBT = "RDBT",
  RDC = "RDC",
  RDCO = "RDCO",
  RDCS = "RDCS",
  RDCT = "RDCT",
  RDDT = "RDDT",
  RDE = "RDE",
  RDHT = "RDHT",
  RDL = "RDL",
  RDMC = "RDMC",
  RDMT = "RDMT",
  RDMV = "RDMV",
  RDRT = "RDRT",
  RDST = "RDST",
  RDT = "RDT",
  RDTC = "RDTC",
  RDTP = "RDTP",
  RDTR = "RDTR",
  RGRP = "RGRP",
  ROUTE = "ROUTE",
  RT = "RT",
  RTRAIN = "RTRAIN",
  RTW = "RTW",
  WB = "WB",
  WE = "WE",
  WL = "WL",
  WMT = "WMT",
  WT = "WT",
  WTSM = "WTSM",
  WV = "WV",
  WVE = "WVE",
}
