import { ApiProperty } from '@nestjs/swagger'

export enum VehicleTypeEnumDto {
  RDTU = "Truck",
  PERSON = "Person for the means of transport human being",
  RC = "Chassis of a railcar",
  RDBT = "Bobtail / Short Tailed Tank Truck",
  RDC = "Chassis of a truck",
  RDCO = "Container",
  RDCS = "Tank Container Semitrailer",
  RDCT = "Tank Container Trailer",
  RDDT = "TKW -2 Achsen Hänger (tank truck -dog trailer)",
  RDE = "Engine of a truck",
  RDHT = "Heavy Trailer",
  RDL = "Loading area (for bulk goods or general cargo)",
  RDMC = "Motor Car",
  RDMT = "Motor Tractor",
  RDMV = "Motor Vehicle",
  RDRT = "TKW Auflieger für weiteren Auflieger (tank truck- b-double front trailer)",
  RDST = "Semitrailer",
  RDT = "Tank of a truck",
  RDTC = "Tank Container Truck",
  RDTP = "Fixed Truck/Trailer Combi-nation",
  RDTR = "Trailer",
  RGRP = "Railcar Group",
  ROUTE = "Route",
  RT = "Tank of a railcar",
  RTRAIN = "Train",
  RTW = "Railcar",
  WB = "Body of a ship",
  WE = "Engine of a ship",
  WL = "Loading area (for bulk goods or general cargo)",
  WMT = "Ship",
  WT = "Tank of a ship",
  WTSM = "Barge (inland navigation vessel)",
  WV = "Vessel (not self-driven, e.g. a barge)",
  WVE = "Vessel / Ship",
}
