
###
POST http://localhost:3000/checkDriver
Content-Type: application/json

{
    "location": "string",
    "userData":
    {
        "cultureInfo":"de",
        "companyId":"string",
        "clientContext":"TOCI"
    }
}


### 
# curl -X POST "http://localhost:3000/checkDriver" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"location\":\"string\",\"userData\":{\"cultureInfo\":\"de\",\"companyId\":\"string\",\"clientContext\":\"TOCI\"}}"

###
POST http://localhost:3000/checkDriver
Content-Type: application/json

{
    "location": "string",
    "userData": 
        {
          "cultureInfo":"string",
          "companyId": "string",
          "clientContext": "string",
          "userIdData":
            {"lastName": "string"}
        },"driver":
    {
        "lastName":"string"
    }
}